//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.TravelRequests = new HashSet<TravelRequest>();
            this.TravelRequests1 = new HashSet<TravelRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<TravelRequest> TravelRequests { get; set; }
        public virtual ICollection<TravelRequest> TravelRequests1 { get; set; }
    }
}
