//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelRequest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PickupPlace { get; set; }
        public Nullable<int> DestinationPlace { get; set; }
        public System.DateTime TravelDateTime { get; set; }
        public string EmailAddress { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
